CREATE TABLE Gestante (
    IdGestante INT PRIMARY KEY IDENTITY(1,1),
    NombresApellidos NVARCHAR(255) NOT NULL DEFAULT '',
    IdNacionalidad INT NOT NULL,
    IdTipoDocumento INT NOT NULL,
    NumeroDocumento NVARCHAR(MAX) NOT NULL DEFAULT '',
    Edad INT NOT NULL,
    IdTipoRegimenSalud INT NOT NULL,
    NombreAseguradora NVARCHAR(MAX) NOT NULL DEFAULT '',
    IdPertenenciaEtnica INT NOT NULL,
    IdGrupoPoblacional INT NOT NULL,
    IdAreaOcurrencia INT NOT NULL,
    IdDptoResidencia INT NOT NULL,
    IdMunicipioResidencia INT NOT NULL,
    DireccionResidencia NVARCHAR(MAX) NOT NULL DEFAULT '',
    IdDptoAtencion INT NOT NULL,
    IdMunicipioAtencion INT NOT NULL,
    Telefono NVARCHAR(MAX) NOT NULL DEFAULT '',
    FechaPosibleParto DATETIME NULL,
    SeRealizaControlPrenatal INT NULL,
    EdadGestacionalSemanas INT NULL,
);
